apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: can-phase-final-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - can.akrzen.cloud
    secretName: can-phase-final-tls
  rules:
  - host: can.akrzen.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: can-phase-final-service
            port:
              number: 80